name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set-env
      run: |
        export CDS_HOME=`pwd`
        echo $CDS_HOME
        ls
        cd src
        make test_vm 
